export const JWT_CONFIG = {
    ACCESS_TOKEN_SECRET: 'JWT_ACCESS_TOKEN_SECRET',
    ACCESS_TOKEN_EXPIRATION: 'JWT_ACCESS_TOKEN_EXPIRATION_MS',
    REFRESH_TOKEN_SECRET: 'JWT_REFRESH_TOKEN_SECRET',
    REFRESH_TOKEN_EXPIRATION: 'JWT_REFRESH_TOKEN_EXPIRATION_MS',
};
