export const S3_CONFIG = {
    REGION: 'BUCKET_REGION',
    BUCKET_NAME: 'BUCKET_NAME',
    ACCESS_KEY: 'ACCESS_KEY',
    SECRET_ACCESS_KEY: 'SECRET_ACCESS_KEY',
    BASE_CLOUDFRONT_URL: 'BASE_CLOUDFRONT_URL',
    CLOUDFRONT_KEY_PAIR_ID: 'CLOUDFRONT_KEY_PAIR_ID',
    CLOUDFRONT_PRIVATE_KEY: 'CLOUDFRONT_PRIVATE_KEY',
} as const;